# The following redirect is intended for use with most SPAs that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# When `now` branch is built, a specific API root URL is setup
[context.now.environment]
  REACT_APP_STATIC_API = "https://bestofjs.michaelrambeau.now.sh"